---
- name: Add HBAC service to rule in IDM 
  hosts: "{{ HOSTS | default('ipaserver') }}"
  vars_files: ipa_admin_creds.yml
  collections:
    - freeipa.ansible_freeipa
  tasks:
    - name: add service to a HBAC rule
      ipahbacrule:
        ipaadmin_principal: "{{ ipa_admin_user | default(omit) }}"
        ipaadmin_password: "{{ ipa_admin_password }}"
        name: "{{ ipa_hbac_rule_name }}"
        hbacsvc: "{{ ipa_hbac_service_name }}"
        action: member
        
