---
- name: Create HBAC rule in freeipa 
  hosts: "{{ HOSTS | default('ipaserver') }}"
  vars_files: ipa_admin_creds.yml
  collections:
    - freeipa.ansible_freeipa
  tasks:
    - name: create a HBAC rule
      ipahbacrule:
        ipaadmin_password: "{{ ipa_admin_password }}"
        name: "{{ ipa_hbac_rule_name }}"