---
- name: create a user in our IDM instance
  hosts: "{{ HOSTS | default('ipaserver') }}"
  vars_files: idm_admin_creds.yml
  collections:
    - freeipa.ansible_freeipa
  tasks:
    - name: Create an IDM User
      ipauser:
        ipaadmin_password: "{{ ipa_admin_password }}"
        name: "{{ ipa_user_name }}"
        first: "{{ firstname }}"
        last: "{{ lastname }}"
        phone: "{{ phone_number }}"
        email: "{{ email_address }}"
        password: "{{ ipa_user_pass }}"
        update_password: on_create