---
- name: create a user in our freeipa instance and add to a new or existing group
  hosts: "{{ all | default('ipaserver') }}"
  vars_files: ipa_admin_creds.yml
  collections:
    - freeipa.ansible_freeipa
  tasks:
    - name: Create an ipa User
      ipauser:
        ipaadmin_principal: "{{ ipa_admin_user | default(omit) }}"
        ipaadmin_password: "{{ ipa_admin_password }}"
        name: "{{ ipa_user_name }}"
        first: "{{ ipa_user_firstname }}"
        last: "{{ ipa_user_lastname }}"
        phone: "{{ ipa_user_phone_number }}"
        email: "{{ ipa_user_email_address }}"
        random: true
        update_password: on_create
    
    - name: Create an ipa Group
      ipagroup:
        ipaadmin_principal: "{{ ipa_admin_user | default(omit) }}"
        ipaadmin_password: "{{ ipa_admin_password }}"
        name: "{{ ipa_group_name }}"

    - name: add user to ipa group
      ipagroup:
        ipaadmin_principal: "{{ ipa_admin_user | default(omit) }}"
        ipaadmin_password: "{{ ipa_admin_password }}"
        name: "{{ ipa_group_name }}"
        user:
          - "{{ ipa_user_name }}"
        action: member