---
- name: create or update a sudo rule in our freeipa instance
  hosts: "{{ HOSTS | default('ipaserver') }}"
  vars_files: ipa_admin_creds.yml
  collections:
    - freeipa.ansible_freeipa
  tasks:
    - name: Create or update an ipa sudo rule
      ipasudorule:
        ipaadmin_principal: "{{ ipa_admin_user | default(omit) }}"
        ipaadmin_password: "{{ ipa_admin_password }}"
        name: "{{ ipa_sudo_rule }}"
        allow_sudocmdgroup: "{{ ipa_sudo_cmd_group }}"
        group: "{{ ipa_group_name }}"
        hostgroup: "{{ ipa_hbac_hostgroup_name }}"
        runasusercategory: "all"
        runasgroupcategory: "all"