---
- name: delete a sudo command group in our freeipa instance
  hosts: "{{ all | default('ipaserver') }}"
  vars_files: ipa_admin_creds.yml
  collections:
    - freeipa.ansible_freeipa
  tasks:
    - name: delete an ipa sudo command group
      ipasudocmdgroup:
        ipaadmin_principal: "{{ ipa_admin_user | default(omit) }}"
        ipaadmin_password: "{{ ipa_admin_password }}"
        name: "{{ ipa_sudo_cmd_group }}"
        state: absent
