---
- name: reset a user password in our freeipa instance
  hosts: "{{ all | default('ipaserver') }}"
  vars_files: ipa_admin_creds.yml
  collections:
    - freeipa.ansible_freeipa
  tasks:
    - name: reset a user password
      ipauser:
        ipaadmin_principal: "{{ ipa_admin_user | default(omit) }}"
        ipaadmin_password: "{{ ipa_admin_password }}"
        name: "{{ ipa_user_name }}"
        random: true
        update_password: always