---
- name: unlock a user in our IDM instance
  hosts: "{{ HOSTS | default('ipaserver') }}"
  vars_files: idm_admin_creds.yml
  collections:
    - freeipa.ansible_freeipa
  tasks:
    - name: Unlock an IDM User
      ipauser:
        ipaadmin_password: "{{ ipa_admin_password }}"
        name: "{{ ipa_user_name }}"
        state: unlocked
